# Generated by Django 4.0.4 on 2022-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_start', models.CharField(max_length=30)),
                ('public_end', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('page', models.CharField(max_length=30)),
            ],
        ),
    ]
